cmake/EthCompilerSettings.cmake

This is a cherry-pick from Dizeeee/cpp-ethereum@8fe011b6c4af46919ccbcf740270830d23c5c950 and can be found in Genoil/cpp-ethereum#254

Fix Compiler Settings Error (by Dizeeee)

---

ethminer/main.cpp
libdevcore/CommonData.cpp
libdevcore/CommonData.h

Set some AMD driver controlling environmental variables to allow bigger buffer allocation.

Set GPU driver env vars

---

.gitmodules
cmake/HunterGate.cmake

Tested on Ubuntu 16.04.
Fix for https://github.com/ethereum-mining/ethminer/issues/219

Hunter disabled mode

---

libethash-cuda/CMakeLists.txt

Fix for building CUDA lib without openCL lib

---

ethminer/MinerAux.h

Add note in usage about protocol requirements for hashrate reporting

---

README.md

Fixed numbers

---

ethminer/MinerAux.h
libapicore/ApiServer.cpp
libapicore/ApiServer.h
libethcore/Farm.h

This PR adds the current uptime in Hours+Minutes to the CLI.
API also uses the same info.
Closes: #301

Added uptime to cli

---

ethminer/MinerAux.h
libethash-cl/CLMiner.cpp
libethash-cl/CLMiner.h
libethash-cl/CLMiner_kernel.cl

I incorporated a lot of the changes from sgminer into CLMiner_kernel.cl. I also added an option to change THREADS_PER_HASH to 1,2,4 or 8. Depending on which card you have, and what environment you're on this can increase performance quite a bit.
This is still pretty experimental, it can require quite a bit of tuning if you change THREADS_PER_HASH to something other than 8.

New OpenCL kernel

---

README.md

Added 8 and expanded on 4

---

libethash-cuda/ethash_cuda_miner_kernel.cu

Fixes an error introduced by https://github.com/ethereum-mining/ethminer/pull/353

fixed dumb error 

---

circle.yml
libethash-cuda/CMakeLists.txt

Add compatibility with compute capability 7.0

---

libethash-cuda/CUDAMiner.cpp
libethash-cuda/CUDAMiner.h
libethash-cuda/ethash_cuda_miner.cpp
libethash-cuda/ethash_cuda_miner.h

This is similar set of patches as were applied to CL Miner.
It still has some issues is not able to find solutions. Testing welcome.

Cleanup CUDA Miner

---

libstratum/EthStratumClient.cpp
libstratum/EthStratumClient.h

Kept allocating new timers without ever deleting them.

Fix stratum timer memory leak

---

ethminer/MinerAux.h
libapicore/ApiServer.cpp
libethcore/Farm.h
libstratum/EthStratumClient.cpp

Provide API with pool addresses such that they can be reported to the client

Issue505 - provide pool addresses to API

---

libstratum/EthStratumClient.cpp
libstratum/EthStratumClientV2.cpp
libstratum/EthStratumClientV2.h

Failover needs to work for stratum V2
Also plug a path where the timer was not rearmed
in stratum v1

Apply work timer fix to stratum v2

---

libhwmon/wrapadl.cpp
libhwmon/wrapnvml.cpp

Not sure what defines `WIN32`, but it's missing when building with MinGW.

fix _WIN32 ifdef

---

libethash-cl/CLMiner.cpp

Partial fix for 567.
https://github.com/ethereum-mining/ethminer/issues/567
Stales aren't flagged as stale yet, but the nonce is matched to the proper WorkPackage.

match stale solutions to correct header

---

libstratum/EthStratumClient.cpp

Line things up a little better.
Use color highlighting on new job and
accept/reject messages.
Add emphasis characters on accept/reject
messages for monochrome use.

Console output, purely cosmetic

---

ethminer/MinerAux.h

Apparently untested!
Cuda error in func 'ethash_generate_dag' at line 154 : invalid configuration argument.

Revert broken commit from @rushfire

---

libethcore/Miner.h
libstratum/EthStratumClient.cpp
libstratum/EthStratumClient.h

Only 2 of them, there are more.

Data races fixes

---

ethminer/MinerAux.h

I've tested it the first time in #628  and it was working as expected.  Then did some variable names changes as suggested, however, I accidentally swapped the cudaBlockSize and cudaGridSize in the cuda configure routine and broke it. This version is tested and working as expected.

split CUDA/CL localWorkSize,globalWorkSize vs cudaBlockSize,cudaGridSize

---

.clang-format

Install clang-format 5+.
Use git-clang-format to reformat changed lines.

Add clang-format config

---

libethash-cuda/CUDAMiner.cpp

List pcie info - rework of abandonned PR#516 opened 22 days ago

---

ethminer/MinerAux.h
libdevcore/Log.h
libethash-cuda/CUDAMiner.cpp

Also, what use if the address of the 1st stream buffer to anyone?

Do we really want to print all numbers in blue???

---

ethminer/MinerAux.h
libstratum/CMakeLists.txt
libstratum/EthStratumClient.cpp
libstratum/EthStratumClient.h

Also disconnect stratum V2 client. Nobody is using it as far as I know, in fact it would currently need updating to work properly! Keep the 2 source files around for possible future reference.

Display pool response time

---

README.md

Update README.md - Fix download counters

---

ethminer/MinerAux.h

https://github.com/ethereum-mining/ethminer/issues/600 as descibed here

Branch #359

---

ethminer/main.cpp
libdevcore/Terminal.h

Simple and small PR to add colors on windows.
Mainly based on @DLS-bau  diff in #684 
This closes the mentioned issue and #226 which also adds (more complex) colors on windows

Added colors on windows 10

---

libethash-cl/CLMiner.cpp
libethash-cl/CLMiner.h

Cosmetic fix, nothing special.

Fix forgotten Unstable kernel replacement

---

ethminer/MinerAux.h
libethash-cl/CLMiner.cpp
libethash-cl/CLMiner.h
libethash-cuda/CUDAMiner.cpp
libethash-cuda/CUDAMiner.h
libethcore/Miner.cpp
libethcore/Miner.h
libpoolprotocols/getwork/EthGetworkClient.h
libpoolprotocols/stratum/EthStratumClient.h

Set maximum number of GPUs supported to 32

Apparently 16 is not enough! Increase and parameterize max # of GPUs

---

libhwmon/CMakeLists.txt

Fix proposal to https://github.com/ethereum-mining/ethminer/issues/625

Fix to issue 625 libdl.so.2 DSO missing

---

libpoolprotocols/stratum/EthStratumClient.cpp

Combine stratum log lines, reduce log volume.

---

.gitignore
README.md
ethminer/MinerAux.h
libapicore/ApiServer.cpp
libapicore/ApiServer.h
libethcore/Farm.h
libethcore/Miner.h
libhwmon/wrapadl.cpp
libhwmon/wrapadl.h
libhwmon/wrapamdsysfs.cpp
libhwmon/wrapamdsysfs.h
libhwmon/wraphelper.h

-HWMON works as before
-HWMON 0 works as before
-HWMON 1 shows power for Nvidia cards

Power usage parameterized (Now Nvidia and AMD in both Linux and Windows)

---

ethminer/MinerAux.h
libhwmon/CMakeLists.txt
libhwmon/wraphelper.cpp
libhwmon/wraphelper.h
libpoolprotocols/stratum/EthStratumClient.cpp

Warnings are cluttering build logs

---

ethminer/MinerAux.h
libpoolprotocols/CMakeLists.txt
libpoolprotocols/testing/SimulateClient.cpp
libpoolprotocols/testing/SimulateClient.h

Moved "doSimulation" code from MinerAux to fake PoolClient.
This removes duplicate code and make simulation more "real". For the miner and other classes everything is like the work comes from a real pool.

Moved Simulator Code to fake PoolClient

---

libpoolprotocols/PoolManager.cpp

Switch the farm before logging.

Minor pool manager optimization

---

ethminer/MinerAux.h

Added param to specify mining stats display interval

---

libethash-cuda/CUDAMiner.cpp
libethash-cuda/CUDAMiner.h

Rename variable m_abort to m_new_work.

---

ethminer/MinerAux.h
ethminer/main.cpp
libdevcore/Log.cpp
libdevcore/Log.h
libpoolprotocols/PoolManager.cpp
libpoolprotocols/testing/SimulateClient.cpp

Truncate commit hash to 8 characters

Display last commit hash at startup

---

cmake/EthCompilerSettings.cmake
ethminer/MinerAux.h

Fix MSVC's C4800 warning.

---

libethash-cl/CLMiner.cpp

Shouldn't this call be inside the work loop?
If not, what synchronizes the work loop with the GPU?

Misplaced queue.finish() ???

---

libethash-cl/CLMiner_kernel_experimental.cl
libethash-cl/CLMiner_kernel_stable.cl

Won't make much difference but correct the comparison.
Fixes #980

OpenCl - Hash equal to target is a solution

---

ethminer/MinerAux.h
libpoolprotocols/PoolClient.h
libpoolprotocols/PoolURI.cpp
libpoolprotocols/PoolURI.h
libpoolprotocols/getwork/EthGetworkClient.cpp

ie. http://127.0.0.1:1234/miner1
Should work for both -F and -P parameters

Implement support for getwork miner id using URL path

---

libpoolprotocols/PoolClient.h
libpoolprotocols/PoolManager.cpp
libpoolprotocols/getwork/EthGetworkClient.h
libpoolprotocols/stratum/EthStratumClient.cpp
libpoolprotocols/stratum/EthStratumClient.h
libpoolprotocols/testing/SimulateClient.h

Complete re-design of StratumClient
Whole branch is addressed to solve connection/reconnection/data-parsing problems.

Socket logic adjustments

---

libpoolprotocols/PoolManager.cpp
libpoolprotocols/stratum/EthStratumClient.cpp
libpoolprotocols/stratum/EthStratumClient.h

Stratum implementation revised.
Sanity checks over rpc messages
Json messages built using Json::Value instead of string concatenation
(better readable)
Adjusted syntax for eth_SubmitHasrate (requires worker)
Addresses and solves
#1041
#1038
#1036
#1023
#936
#940

Stratum Revised

---

libpoolprotocols/stratum/EthStratumClient.cpp

Disconnect should always invoke onDisconnect.

Urgent ! Disconnect recursion prevention broke onDisconnect event

---

ethminer/MinerAux.h
libpoolprotocols/PoolManager.cpp
libpoolprotocols/stratum/EthStratumClient.cpp

Allow usage of email address in nanopool
Addresses
#1004
#937 
#904
_Email MUST be Path part of URI_ 
should be 
Email **CAN** be placed unencoded in path part
eg. -P
stratum+tcp://ethaddress[.worker][:password]@eth-eu1.nanopool.org:9999[/emailaddress]

-P acceptance of email address

---

libethash-cuda/CUDAMiner.cpp

Nothing functional. Just relocate variables to their
proper scope.

Fix a few more nits in cudaminer

---

libethash-cuda/CUDAMiner.cpp

- In cuda with streams greater than one (default = 2) cuda
would silently drop hash counts for all streams except one
at each job switch.
Fix by making sure that all streams are synchronized and
accounted for, including potential stale solutions, before
exiting the search loop.

Fix cuda hash mis-count (stabilize hash rate)

---

libpoolprotocols/PoolManager.cpp
libpoolprotocols/stratum/EthStratumClient.cpp
libpoolprotocols/stratum/EthStratumClient.h

In case is array or object.
Also reset color "red" for rejected shares.
Addresses #1065

Wrong parsing of "error" json member

---

ethminer/MinerAux.h

Error catching on argument parser --dag-load-mode

---

ethminer/MinerAux.h
libapicore/CMakeLists.txt
libapicore/httpServer.cpp
libapicore/httpServer.h

Implement built-in http server for miner state reports

---

CMakeLists.txt
README.md

Ethminer gives its best is on CUDA

Make build for CUDA default ON

---

libpoolprotocols/stratum/EthStratumClient.cpp

Possible fix for recent stratum auth problems for example: #1112

Handling of stratum method result based on stratum spec.

---

.travis.yml
CMakeLists.txt
appveyor.yml
circle.yml

Fixes https://github.com/ethereum-mining/ethminer/issues/1127.

Upgrade Hunter to 0.21.9

---

libapicore/httpServer.cpp

Add a missing <html> open tag to the httpServer.

httpServer: Fix: Add missing opening <html> tag.

---

CHANGELOG.md

@chfast @jean-m-cyr 
As requested in #1159 I added the changes.

CHANGELOG.md: Add changes of PR1146, PR1159 and PR1162

---

libpoolprotocols/stratum/EthStratumClient.cpp

Should accomplish pools _standards_

Weakened stratum checks to minimal levels

---

ethminer/main.cpp

Also use more consistent error log formatting, and delete unused function.

Make sure at least one pool URL is specified.

---

README.md

Better description of ethminer project.

---

POOLEXSAMPLES_ETH.md

Adding the new -P switch seems to create a lot of issues.
I think it's a good idea to add some documentation how to connect ethminer to a pool.
(As ETC could be different I named the file POOLSAMPLES_ETH.md )
If Issue #1147 is available, this docu could be validated/generated with travis & co. 
I know the documentation is currently not finished (some TODOs, not fully completed)!
But to complete the information I need some feedback and help.
I also test my settings only on linux machines - maybe there is something different on windows (of course - it shouldn't)
So:
* Feel free to Merge the PR and allow more people to collaborate
* Give me feedback and infos - so I can adapt my PR
* As I'm not a native speaker - please check also grammer and typos.

Add POOLEXSAMPLES_ETH.md to show how to connect to different pools.

---

libdevcore/Log.cpp
libdevcore/Log.h
libethash-cl/CLMiner.cpp
libethash-cuda/CUDAMiner.cpp
libpoolprotocols/PoolManager.cpp

- delete never used code or feature
- get rid of type based colorization

Clean up log processing

---

POOL_EXAMPLES_ETH.md

Spell check. Exsamples is driving me nuts -- it's not a word!

Update and rename POOLEXSAMPLES to POOL_EXAMPLES

---

ethminer/main.cpp
libpoolprotocols/PoolClient.h
libpoolprotocols/getwork/EthGetworkClient.cpp
libpoolprotocols/stratum/EthStratumClient.cpp

PoolClient.h have to receive connection (URI) as a pointer

---

ethminer/main.cpp
libethash-cuda/CUDAMiner.cpp
libethash-cuda/CUDAMiner.h

Minor adjustments to CUDA code

Cuda optim

---

ethminer/main.cpp
libpoolprotocols/PoolManager.cpp
libpoolprotocols/PoolManager.h

In case we fall on a failover pool we can set an amount of time to stay there before trying to reconnect back to primary pool.

Very basic implementation of return to primary pool.

---

libethcore/Farm.h
libpoolprotocols/PoolManager.cpp

Pass 200 byte variable by reference, not by value

---

API_DOCUMENTATION.md
ethminer/main.cpp
libapicore/ApiServer.cpp
libapicore/ApiServer.h
libethcore/Farm.h
libethcore/Miner.h
libpoolprotocols/PoolManager.cpp
libpoolprotocols/PoolManager.h
libpoolprotocols/PoolURI.h

* miner_getconnections
* miner_setactiveconnection
* miner_addconnection
* miner_removeconnection

New API methods

---

libethash-cuda/CUDAMiner.cpp

Better logic on workLoop
Removed unnecessary for loop in CUDAMiner::search

Minor optimization for CUDAMiner

---

ethminer/main.cpp

Fix dag load mode help

---

README.md

README: Extend Maintainers & Authors table

---

libhwmon/wrapadl.cpp
libhwmon/wrapadl.h
libhwmon/wraphelper.cpp
libhwmon/wraphelper.h
libhwmon/wrapnvml.cpp
libpoolprotocols/stratum/EthStratumClient.cpp

Clean up _WIN32 defines.

---

libpoolprotocols/PoolClient.h
libpoolprotocols/getwork/EthGetworkClient.cpp
libpoolprotocols/getwork/EthGetworkClient.h
libpoolprotocols/stratum/EthStratumClient.cpp
libpoolprotocols/stratum/EthStratumClient.h
libpoolprotocols/testing/SimulateClient.cpp

Adjusted some CPP Warnings #1264 
Simplified logic for EthGetworkClient
- removed unused variables
- unified behavior (startworking only after connect)

Cpp warnings

---

libethcore/Farm.h

Every segment stop was increased by a multiplier of (i+1)

Correction in segment sizes for miner_getscramblerinfo

---

ethminer/DBusInt.h
libapicore/httpServer.cpp
libethash-cl/CL/cl2.hpp
libethash-cl/CLMiner.cpp
libethash-cuda/CUDAMiner.cpp
libethcore/Farm.h
libethcore/Miner.cpp
libhwmon/wrapadl.cpp
libhwmon/wrapamdsysfs.cpp
libhwmon/wrapnvml.cpp
libpoolprotocols/PoolManager.h
libpoolprotocols/stratum/EthStratumClient.cpp

Kind of pedantic, but raised as an issue...
Fixes #1283

Replace defined NULL with C++ nullptr

---

docs/BUILD.md

/CC @chfast @AndreaLanfranchi @jean-m-cyr 
Please fill in the info for OS'es apart from Windows. Also, I'm not sure if I should list Git as a requirement, i.e not sure if everything compiles from a source archive.
We should probably add a ToC too.
Fixes #1267

First pass on listing build requirements.

---

libapicore/httpServer.h
libdevcore/Exceptions.h
libethash-cl/CLMiner.cpp
libethash-cuda/ethash_cuda_miner_kernel.h
libhwmon/wrapamdsysfs.cpp

Fix a bunch of cppcheck warnings

---

libpoolprotocols/getwork/EthGetworkClient.cpp

Fixes #1288
Also Clang'ed all file.

Missing set of m_connected flag

---

libapicore/ApiServer.cpp

The previous code used `==` to check if the password was correct, which means a sufficiently motivated hacker can extract the password from the server by measuring response times (aka "Timing attack"). I replaced `==` with a constant-time comparison, which checks up to the first 500 bytes of the password & input (that limit can be removed by introducing a collision-resistant compressing hash, like blake2b/sha3, but 500 should suffice and is much easier to implement)

patch timing attack vulnerability in api server

---

docs/API_DOCUMENTATION.md

API_DOCUMENTATION.md: add ToC.

---

libethash-cl/CLMiner_kernel_experimental.cl
libethash-cl/CLMiner_kernel_stable.cl

Prevent out of range node index

Fix OpenCL DAG gen bug

---

docs/API_DOCUMENTATION.md
libapicore/ApiServer.cpp
libethcore/Farm.h
libethcore/Miner.h

As suggested in #1232 we can have more reasons why mining is paused on a specific GPU.

GPU pausing: prepare pausing for multple reasons, add API function to pause

---

libethash-cuda/ethash_cuda_miner_kernel.cu

address https://github.com/ethereum-mining/ethminer/issues/1292

remove non shuffle version in the last pass

---

libapicore/ApiServer.cpp

Add support for API request id as per JSONRPC v2 specs

---

libpoolprotocols/stratum/EthStratumClient.cpp

As per user report here
https://github.com/ethereum-mining/ethminer/pull/1333#issuecomment-402641473
There is an issue with f2pool.com which, in case of wrong login technique, instead of answering back with a Json error message DOES NOT RESPOND AT ALL and begins, after a while, to send jobs.
This PR amends the behavior introducing a timeout on first responses.
It also addresses #1339 which may be caused by the sinchronous cancel of the timer which is triggering the disconnection.

Auto-Stratum refinement

---

libapicore/ApiServer.cpp
libethash-cuda/CUDAMiner.cpp
libpoolprotocols/stratum/EthStratumClient.cpp

Additionally added reuse address socket option in Api Server

Fixes miss of disconnection on response timeout (missing post)

---

libpoolprotocols/stratum/EthStratumClient.cpp

Workaround to nanopool wrong stratum implementation.
See #1348

Nanopool autodetection

---

CMakeLists.txt
ethminer/main.cpp
libapicore/ApiServer.cpp
libapicore/httpServer.cpp
libpoolprotocols/stratum/EthStratumClient.cpp

The buildinfo now has project_name and project_name_with_version fields.

Upgrade Cable

---

libpoolprotocols/stratum/EthStratumClient.cpp

For whatever reason it appears several posts to io_service are still missing.
This should amend #1393

Missing posts to io_service

---

libpoolprotocols/stratum/EthStratumClient.cpp

@AndreaLanfranchi made some excellent changes, but added a bit of duplicated code

Remove duplicated code which was added in #1333

---

libpoolprotocols/PoolManager.cpp

Use unsigned instead of int

---

libpoolprotocols/stratum/EthStratumClient.cpp

Some pools (eg sparkpool) when receiving wrong stratum method (which is essential to detect proper stratum mode) drop connection instead of replying with error.

Stratum autodetection on disconnects

---

scripts/testpools.bash

I created this script to test #1172.
Last days I used it to test #1429.
Maybe it can be used in the future too by someone.

Add script testing different pools.

---

libethash-cuda/CUDAMiner.cpp
libethash-cuda/CUDAMiner.h

- method configureGPU was the only caller of method
cuda_configureGPU. Combine the two methods.

Combine two function.

---

CHANGELOG.md

No code changes... just documentation updates (changelog)

Update changelog with recent changes.

---

libethash-cuda/CUDAMiner.cpp
libethash-cuda/CUDAMiner.h

Nothing new... just refactoring.

init is the only caller of cuda_init, combine methods

---

CHANGELOG.md
libpoolprotocols/stratum/EthStratumClient.cpp

Some minor fixes
* Update Changelog
* Reset Nicehash's relevant members on every (re)connection.

Al 20180820

---

libpoolprotocols/PoolManager.cpp
libpoolprotocols/stratum/EthStratumClient.cpp

* Remove redundant .cancel() methods on timers
* Remove redundant conditional checks
* Reorder lines of code
* Reset m_headers member on new connection

Minor Stratum code optimizations

---

libpoolprotocols/PoolManager.cpp
libpoolprotocols/PoolManager.h

This is only relevant for NiceHash mode.

Dup job check to include extraNonce

---

libdevcore/Log.cpp

Change blue flavour in console output

---

libpoolprotocols/stratum/EthStratumClient.cpp

Stronger checks of stratum validity over ethereumstratum
Amends #1518

mining_setdifficulty method is not part of simple stratum

---

ethminer/main.cpp
libdevcore/CommonData.cpp
libdevcore/CommonData.h
libdevcore/Exceptions.h
libdevcore/FixedHash.cpp
libdevcore/FixedHash.h
libdevcore/Guards.h
libdevcore/Log.cpp
libdevcore/Log.h
libdevcore/RLP.cpp
libdevcore/RLP.h
libdevcore/Worker.cpp
libdevcore/Worker.h
libethash-cuda/CUDAMiner.cpp
libethash-cuda/CUDAMiner.h
libethcore/EthashAux.cpp
libethcore/EthashAux.h
libethcore/Exceptions.h
libethcore/Farm.h

- Replace project name in all GPL comment headers
- Contains no functional changes

Replace cpp-ethereum with ethminer

---

ethminer/main.cpp

Correct ethminer --help

---

.gitattributes
.travis.yml
libethash-cuda/CUDAMiner.cpp
libhwmon/wrapadl.cpp
libhwmon/wrapamdsysfs.cpp
libhwmon/wrapnvml.cpp
libpoolprotocols/stratum/EthStratumClient.cpp
scripts/check_code_format.py

Add a small code format check before any compilation starts on travis:
Check in *.cpp and *.h following things:
* UNIX lineendings
* No tab as indent
* No trailing whitespaces

Travis code format check

---

libpoolprotocols/stratum/EthStratumClient.cpp

Bad error in timeout comparison check.
Please merge urgently

Wrong order of comparison

---

docs/API_DOCUMENTATION.md

Should be params not data

---

libpoolprotocols/PoolManager.cpp

Prior method stepped to previous available

Adjust pool rotation to next available

---

libapicore/httpServer.cpp

* switch to HTML5
* use the system font stack
Note that I haven't tested if it even builds :) Please try it locally and confirm you like the changes.
I kept the table border style and padding to what it was BTW.

API Server: Modernize HTML.

---

docs/API_DOCUMENTATION.md

Use "```js" to mark a json format.

Correct API_DOCUMENTATION.md.

---

CMakeLists.txt
ethminer/main.cpp
libapicore/ApiServer.cpp
libdevcore/Log.h
libethash-cl/CLMiner.cpp
libethash-cuda/CUDAMiner.cpp
libethash-cuda/CUDAMiner.h
libethcore/Miner.h
libpoolprotocols/stratum/EthStratumClient.cpp

- Allow measurement of software evaluation time on any CPU.

Enable/disable logged developer output at build time - Revert CUDA search

---

ethminer/main.cpp

Missing documentation about SSL_CERT_FILE environment variable for *nix

SSL_CERT_FILE env var

---

ethminer/main.cpp
libethash-cl/CLMiner.cpp
libethash-cuda/CUDAMiner.cpp
libethcore/EthashAux.h
libethcore/Farm.h
libethcore/Miner.h
libpoolprotocols/PoolClient.h
libpoolprotocols/PoolManager.cpp
libpoolprotocols/getwork/EthGetworkClient.cpp
libpoolprotocols/getwork/EthGetworkClient.h
libpoolprotocols/stratum/EthStratumClient.cpp
libpoolprotocols/stratum/EthStratumClient.h
libpoolprotocols/testing/SimulateClient.cpp
libpoolprotocols/testing/SimulateClient.h

Please review esp. commit eec3319b2e03fefefaaf20b9fbcc49544b7a168c !

Cleanup, Cosmetics & Rework

---

docs/BUILD.md
docs/POOL_EXAMPLES_ETH.md

Minor Document Changes

---

appveyor.yml

* switched to the CUDA SDK from this repo
* added CUDA 10 with the default MSVC 2017 compiler
* kept CUDA 9.0 build, not sure if we want this or not
ref #1594

Windows: Add CUDA 10, build both binaries

---

libethash-cuda/CMakeLists.txt

Since we don't use macros defining CUDA arch, this should do for now.

Cuda 10 dirty fix

---

ethminer/main.cpp

@chfast: Do we really still need that dbus stuff? (API is available getting much more infos)

Fix build issue when using -DETHDBUS=ON.

---

libethash-cuda/dagger_shuffled.cuh
libethash-cuda/ethash_cuda_miner_kernel.cu
libethash-cuda/ethash_cuda_miner_kernel.h
libethash-cuda/ethash_cuda_miner_kernel_globals.h

https://github.com/ethereum-mining/ethminer/pull/1653
Revert "Merge pull request #1653 from ethereum-mining/deleteHeader2"
This reverts commit 000e8d70444411d03a774264ec0ffd161821eebc, reversing
changes made to 28b147b7e43e9bb58685d8838f78b9c9da976627.

Revert "Move global definitions" PR

---

libethash-cuda/dagger_shuffled.cuh
libethash-cuda/ethash_cuda_miner_kernel.cu

Rewrote switch to single instruction in dagger_shuffled, added const to constant variables

Minor cleanups in Ethash Cuda

---

ethminer/main.cpp
libdevcore/Log.cpp
libdevcore/Log.h

- By default log goes to stderr to maintain backwards compat.

Optionally send log output to stdout

---

libpoolprotocols/stratum/EthStratumClient.cpp

Adjusts proper order of calls to onConnected so Farm is **always** started **before** receiving jobs.

Amend missing calls to onConnected

---

libethash-cuda/dagger_shuffled.cuh
libethash-cuda/ethash_cuda_miner_kernel.cu
libethash-cuda/ethash_cuda_miner_kernel_globals.h

If you're going to use macros, might as well take full advantage...

Clean up CUDA-8 shuffle patch

---

libpoolprotocols/PoolManager.cpp

Only relevant for API calls (mainly removeConnection()).

Little adjustment on async gates logic

---

libapicore/ApiServer.cpp

Check if even one parameter is passed to miner_setscramblerinfo().

Fix apiminer setscramblerinfo

---

appveyor.yml

cache `C:\CUDA\v*` to reduce build time.

appveyor: cache C:\CUDA\*

---

libpoolprotocols/stratum/EthStratumClient.cpp

Missing break(s) in case sequence

Amend case fall through

---

libethash-cl/CLMiner.cpp

Using ClPlatformTypeEnum::Clover.

opencl: support Intel Gen OCL Driver

---

libethash-cpu/CPUMiner.cpp

Please let me know if I need to do anything else before getting a review :)

Support CPU Mining on Mac OSX

---

libapicore/ApiServer.cpp

fixing non responsive API

---

CMakeLists.txt

Update Hunter in order to fix build issue with powerpc64le arch.

---

README.md

Haven't done any work for ethminer in a long time so it is not fair that my address is still on the board.
Thank you to everyone for the great times!

Readme.md: removed my ETH address

---

libethash-cl/CLMiner.cpp

set the `PLATFORM` as intended.
please see a5be252960a
fix regression bug caused by commit 5efd47caa0.

set PLATFORM correctly.

---

libethash-cuda/ethash_cuda_miner_kernel.cu

As currently implemented, this kernel attempts to do SHA3 on the object 'dag_node' which is 16 uint2's long (hash128_t = 128 bytes = 32 uints = 16 uint2's), but SHA3 expects to receive a pointer to an array of 25 uint2's. It's pure luck that it works correctly with CUDA. 
I've managed to port this whole project to ROCm and I'll make a separate pull request for that, but this is one of the issues I found during porting (SHA3 was malfunctioning and that resulted in incorrect data in the dag buffer.) It probably need to be fixed regardless. it might break with CUDA too after some change in the compiler, and you'll spend ages tracking down the cause of the breakage.

Avoiding buffer overflow in SHA3
