- ethminer/MinerAux.h
A typo for the --cuda-parallel-hash switch snuck through to the help file – this fixes it
> Fix typo in help for --cuda-parallel-hash switch

- CMakeLists.txt
Update to newer hunter version.
Fixes this Visual Studio 2017 Community error:
[hunter ** INTERNAL **] vcvarsall.bat not found in `C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC`
> Update to newer hunter version

- libethash-cl/ethash_cl_miner.cpp
- libethash-cl/ethash_cl_miner.h
Simplify sync with OpenCL by removing pending workset queue.
I've noticed 0.1% performance improvement.
> OpenCL: Single search buffer to lower latency

- libethash-cl/ethash_cl_miner.cpp
Update OpenCL defaults to the same as CUDA. Reasons:
- After this fix my AMD Tonga card no longer TDRs running ethminer --benchmark
- Currently m_localWorkSize (MinerAux.h) has different values for OpenCL if ETH_ETHASHCUDA is defined
I believe this will also fix https://github.com/ethereum-mining/ethminer/issues/78
> Make OpenCL default work size consistently the same as CUDA

- libdevcore/CommonData.h
This fixes https://github.com/ethereum-mining/ethminer/issues/151 issue in stratum encoding of found nonce.
> Fix invalid nonce size

- ethminer/main.cpp
The defines from `BuildInfo.h` where missing.
> include BuildInfo.h

- ethminer/MinerAux.h
Flag no longer exists, but lingers in help text
Also removes a comment that referred to a deleted line
Cleanup after 2c506663c5bd6ad5f496e83d94abdbf9327bb6e1
> Remove help entry for --cuda-extragpu-mem

- ethminer/MinerAux.h
- libdevcore/Worker.h
- libethash-cl/CLMiner.cpp
- libethcore/EthashCUDAMiner.cpp
- libethcore/Farm.h
- libethcore/Miner.h
The farm sometimes sends empty work package to miners. The setWork() has magic side effects of restarting miners. We want to get rid of this -- miners should not be restarted this way.
> Do to set empty work

- ethminer/MinerAux.h
- libethash-cl/CLMiner.cpp
- libethash-cl/CLMiner.h
- libethcore/EthashAux.h
- libethcore/Miner.h
- libstratum/EthStratumClient.h
- libstratum/EthStratumClientV2.h
This should be equivalent of #4.
> CLMiner: Optimization for frequent work updates

- ethminer/MinerAux.h
- libdevcore/Terminal.h
- libethcore/Farm.h
- libethcore/Miner.h
- libstratum/EthStratumClient.cpp
- libstratum/EthStratumClientV2.cpp
I added hashrate per card, and colors for accepted/refused shares.
> Hashrate printed per card.

- libethash-cuda/CMakeLists.txt
Since @chfast suggested in #208 to just create a PR with this, i now did.
Not really sure if supporting compute_62 / sm_62  is really needed tho.
It seems this is for a new generation of chips? Most likely for cars? Or a SOC like targa.
Well here is the PR anyways, this should fix the #208 issue :D
> Add support for compute_62 / sm_62

- ethminer/MinerAux.h
- libstratum/EthStratumClient.cpp
- libstratum/EthStratumClient.h
- libstratum/EthStratumClientV2.cpp
- libstratum/EthStratumClientV2.h
This PR adds reporting the current hashrate to the pool, also known as Reported Hashrate.
This should fix #49 
Since Stratum does not support reporting the hashrate i looked at what claymore miner is using. 
As it turns out, most (if not all) communication of claymore is jsonrpc.
This also is the case for hashrate reporting. So i implemented it that way too.
Also since there are two stratum client versions i added the method to both.
Tested on ethermine.org
> Added: reporting current hashrate to pool

- CMakeLists.txt
- CODEOWNERS
- ethminer/CMakeLists.txt
- ethminer/DBusInt.h
- ethminer/MinerAux.h
Some initial D-Bus support. It constantly reports current hash rate using D-Bus so it can be caught by external application (for monitoring purposes). To compile with D-Bus support add "-DETHDBUS=ON" to cmake command. D-Bus interface is "eth.miner.monitor". Signal name is "Hash".
> Add D-Bus support

- ethminer/MinerAux.h
This fixes mixed card mining if not in stratum mode.
Tested on windows only.
Closes #123 and closes #243
> Fix mixed card mining for farm/getwork mode. #123 #243

- libethash-cl/CLMiner.cpp
- libethash-cuda/ethash_cuda_miner.cpp
* Fixes CUDA Compute Version display
My CUDA Cleanup PR added huge spaces between the version number by displaying the compute version after card detection, this fixes it.
* Adds platformID and correct DeviceID for ``--list-devices``
It seems to be a big cause of confusion using ``--opencl-devices`` and ``--opencl-platform``. This is partly due to a bad listing of the openCL devices. This PR fixes this, by displaying the platformId AND the DeviceId. Also since (at least i think so) the devices are indexed per platform the deviceId resets per platform to 0
Listing OpenCL devices.
FORMAT: [platformID] [deviceID] deviceName
[0] [0] Intel(R) HD Graphics 4000
CL_DEVICE_TYPE: GPU
CL_DEVICE_GLOBAL_MEM_SIZE: 662700032
CL_DEVICE_MAX_MEM_ALLOC_SIZE: 165675008
CL_DEVICE_MAX_WORK_GROUP_SIZE: 512
[1] …
> Couple of small display related fixes

- ethminer/MinerAux.h
- libethcore/Farm.h
Hashrate will now be smoothed/averaged before display, also the shown hashrate is no longer affected by when the rate is read. It also is not affected by set work.
Currently it averages the last 10 seconds. so if you playing around with clocks you need to wait a bit longer now.
> Added smoothing of displayed hashrate, should no longer jump that much.

- ethminer/MinerAux.h
The stratum-failover argument handling in the existing implementation is not consistent. The existing code implements: stratum-failover and FS. However, the help screen uses both --stratum-failover and --failover-stratum. --failover-stratum is not actually implemented in the code, only the abbreviation FS is. This change modifies the code to use SF and --stratum-failover to be more consistent across the board.
> Update to fix stratum failover argument handling

- libethash-cuda/CUDAMiner.cpp
With difficulty increasing, 12 digits don't give us any idea of the actual target!!! Makes for confusing log since 0 is the hardest possible target! Add 10 digits.
> 10 digit target always 0 in log messages!!!

- ethminer/MinerAux.h
- libethash-cuda/CUDAMiner.cpp
- libethash-cuda/ethash_cuda_miner.cpp
- libethash-cuda/ethash_cuda_miner.h
- libethash-cuda/keccak_u64.cuh
- libethcore/Miner.cpp
- libethcore/Miner.h
- libhwmon/wrapnvml.cpp
- libstratum/EthStratumClient.cpp
- libstratum/EthStratumClientV2.cpp
- Don't waste time formatting output text before sending problem to GPU.
- Don't waste time formatting output text before sending solution to pool.
- Give more detail in stratum new job log such that we don't have to spit it out for each cards.
- Remove uneccessary use of volatile. There are no read/modify/write scenarios that need to be atomic.
> Clean up and minor optimizations

- libethash-cuda/ethash_cuda_miner_kernel.cu
It seems the values for --cuda-parallel-hash as 3, 5, 6, 7 does not make sense. So limit the size of the binary.
> CUDA: Limit number of options for parallel hashes

- libethash-cl/CLMiner.cpp
Adding a function ``strClError`` which translates error codes into readable errors.
Unify cl error format by introducing a new macro ``ETHCL_ERR()``. The new errors are printed in the format:
``message: cause, readable error (error code)``
I went ahead and moved ``strClError`` into the CLMiner class, as it is very specific to CL and I couldn't find a CL namespace.
Closes #230
> Rework OpenCL error printing

- libdevcore/CMakeLists.txt
- libethash-cuda/CUDAMiner.cpp
- libethcore/Farm.h
* Add stopWorking() to destructor before pause() to prevent workLoop from continuing on deleted members.
* Scope minerWork lock to just the m_miners member, preventing deadlock with collectHashRate.
* Fix race with hashrateTimer by canceling and removing after serviceThread is joined to prevent retriggering the timer in serviceThread.
* Add boost::system to target_link_libraries for devcore for those that don't compile with stratum.
> Fix segfault and deadlock in CUDAMiner.

- ethminer/MinerAux.h
- libethash-cl/CLMiner.cpp
- libethash-cuda/CUDAMiner.cpp
- libethash-cuda/ethash_cuda_miner.cpp
- libethash-cuda/ethash_cuda_miner.h
- libethash-cuda/ethash_cuda_miner_kernel.cu
- libethcore/EthashAux.h
- libethcore/Miner.h
- libstratum/EthStratumClient.cpp
- libstratum/EthStratumClient.h
- libstratum/EthStratumClientV2.cpp
- libstratum/EthStratumClientV2.h
This accomplishes the initial goal of eliminating the double
evaluation of solutions as well as supports the virtually
impossible case of a single thread grid finding more than one
solution. The goal this time around was not to monkey with
the thread model. This doesn't alter or resequence any software
locks. I'd bet that if this one locks up, then the master
code probably does as well!
As it turns out the low level C++ GPU result handler knows
when it's sending invalid solutions up the stack. It just
had no way of telling stratum about it. It seems that is
the whole reason a copy of the previous job is held and the
rechecking of the solution was done in submit. Someone
figured where these rare apparent invalids were coming from
and added a re-evaluation in submit, if that passed the …
> No duplicate evals, no invalid shares, minimal diff

- libethash-cuda/CUDAMiner.cpp
- libethash-cuda/ethash_cuda_miner.cpp
- libethash-cuda/ethash_cuda_miner.h
The n part of the parameter is presently ignored
in single mode for cuda. GPU 0 always does the
calculation. Fix that.
GPU power consumtion increases 25% during dag
calculation, and pushing supply limit. Could
use sequential, but single is faster. Also
prefer to do the single calculation on selected
lowest power gpu.
> Honor the -L single <n> cmd line parameter

- libethash-cuda/ethash_cuda_miner.cpp
Many of the current open issues are from people, that don't understand that you can't mine ethereum with a GPU with less than 3GB RAM
https://github.com/ethereum-mining/ethminer/issues/449
> Check whether the device has enough RAM whenever we create the DAG

- libethash-cl/CLMiner.cpp
- libethash-cl/CLMiner.h
Instances of CLMiner are started concurrently. Apparently, CLMiner::init
has a race condition and should not run concurrently. A static mutex is
added to prevent this race condition.
This problem exists for me since a long time. With the latest stable release - 1.2 i think - i had the issue as well but it didnt occur always so i could work around it by trial and error, sometimes ethminer would not crash on startup. With recent code changes, it became worse and it almost always crashed.
These problems disappeared after this fix. I only tested it on Win10.
I am using 2x RX 480.
Side note: it could be cleaner to move things which should only be done once from init() to maybe the constructor, or some public method which should be called from outside once - the caller is then responsible to …
> Fix race condition in CLMiner::init through mutex

- libethash-cl/CLMiner_kernel_unstable.cl
The Mesa/Clover support has been broken in commit b1a152b2045139a052e5c3e643a72c9f05e91bae / #294
This commit reverts the removed Clover lines before the above commit.
Fixes #444, #443
> libethash-cl: restore Mesa/Clover support in unstable kernel

- libstratum/EthStratumClient.cpp
The IO timeout handler was never bound to the io service.
TCP timeouts as well as timer timeouts would never be caught.
No recovery or failover would work!
> IO timeout not working. Failover and reconnect not happening!

- cmake/EthCheckCXXFlags.cmake
- cmake/EthCompilerSettings.cmake
Under gcc enable dead code and data stripping.
Removes about 20K from executable. Not much, but
its free.
I believe clang supports these flags as well.
> Strip unused (dead) code and data sections

- libdevcore/Log.cpp
- libdevcore/Log.h
Create a copy of the constant parameter, append a new-line, send it with single << operator
> Prevent concatenated console lines

- libethash-cl/CLMiner.cpp
- libethash-cl/CLMiner.h
- libethash-cuda/CUDAMiner.cpp
- libethash-cuda/CUDAMiner.h
- libethcore/Farm.h
- libethcore/Miner.h
When it gets new work the farm calls setWork for each
GPU’s miners.
For an nvidia GPU miner, setWork:
- Sets a flag for the miner to stop. The miner will not
acknowledge this flag till it completes its current
calculation pass, on average half of one hash
calculation’s time.
- Wait for the miner to stop (blocks).
- Reset the miner with new work.
This has performance and cost consequences. Since the
farm calls setWork sequentially over all miners, a miner
will not be stopped and informed of new work, till the
previous has completed the reset. It also means that
because of this, the laer a miner restarts the more
likely to provide a stale share working on old work
instead of getting started new work.
To mittigate this we break up the setWork process in
two parts: setWork and waitReady. …
> Halve the nvidia farm switch time.

- libethash-cuda/CUDAMiner.cpp
- libethash-cuda/CUDAMiner.h
- libethash-cuda/ethash_cuda_miner.cpp
- libethash-cuda/ethash_cuda_miner.h
Fix fixes the race condition when the pool thread has a new work package already. The work package is passed along with the nonce now to make sure that the solution reported is valid.
This requires to change the signatures of multiple function, but it should be simplified a lot after ethash_cuda_miner is merges with CUDAMiner.
> CUDAMiner: Pass work package to report()

- ethminer/MinerAux.h
A minor fix to allow the -rh option to stand anywhere
see https://github.com/ethereum-mining/ethminer/issues/464
> fixed #464; Position of -RH option

- ethminer/MinerAux.h
This code should launch CUDA initialization process while in mixed mode and should not be coded as if/else statements but if/if .
This patch should fix the issue #553
> make sure to initialize the correct number of CUDA devices in mixed mode -X param

- libethash-cl/CLMiner.cpp
- libethash-cuda/CUDAMiner.cpp
- libethcore/EthashAux.h
- libstratum/EthStratumClient.cpp
The current code assumes the incoming job number will always be 8 hex
characters long; this currently breaks with nicehash, which is sending
16 hex character job numbers like '000000047fa89505'.
This commit fixes the issue by storing the incoming job number length in
WorkPackage and Solution, then using it to truncate the stored job
number back to whatever the original length was.
It also fixes a closely issue where the padding, which added 56 `0`s,
was padding out to 72 characters; the fix here resizes directly to 64
characters, whatever the input size.
Fixes #563 (#588 didn't entirely fix it, as per the above).
> Fix ethereumstratum when job number is >8 chars

- libethash-cl/CLMiner.cpp
- libethash-cuda/CUDAMiner.cpp
- libethcore/Farm.h
- libethcore/Miner.h
We don't want to delay a job switch with an expensive
random number generation. Besides this approach does
not guarantee that two GPU will not be given overlapping
search ranges (highly unlikely but possible).
Instead we give each GPU its own unique 2^40 nonce
range to search and we do it very efficiently.
> No need to call the randomizer with each new job.

- libethash-cuda/CUDAMiner.cpp
R13 ignores this parameter for cuda and
does parallel load instead. This corrects
the issue.
> CUDA: -L sequential parameter is broken

- ethminer/MinerAux.h
without this change while in mixed mode -x then --cl-local-work, --cl-global-work  would also affect CUDA side. should fix #627
> decouple local/work group sizes for CUDA and CL

- libethash-cuda/CUDAMiner.cpp
- libethash-cuda/dagger_shuffled.cuh
- libethash-cuda/ethash_cuda_miner_kernel.cu
- libethash-cuda/ethash_cuda_miner_kernel.h
Given that we trust our GPUs there is no good reason
to recalculate the mix hash in software. The GPU has
already calculated it in order to find the nonce.
So, we get CUDA to provide us with the mix hashes
corresponding to each found solution, and send that
off to the pool insted of the recalculated one which
would be identical anyway!
What was it? Another 6ms. saved, I think.
> CUDA: Eliminate software evals completely! 

- libethash-cuda/CUDAMiner.cpp
- libethash-cuda/CUDAMiner.h
Though not strictly required since we know the specifics
of the case, play by the rules of engagement
in a multithreaded/multiprocessor environment.
> CUDA: Use atomic rather than relying on special case

- ethminer/MinerAux.h
- ethminer/main.cpp
But since we only support stratum 1 enforce that choice.
I doubt anyone is using any other value successfully.
Also, it's probably not productive to core dump on a parameter
error.
> Retain the stratum version control variable for future use

- libethash-cuda/cuda_helper.h
- libethash-cuda/ethash_cuda_miner_kernel.h
Some portions of the code were not using the correct
SAFE_CALL. This might help elucidate this misterious
'ghost mining' problem some are seeing. Hash rate normal
but no shares found!
> Make sure everyone uses the exception handlers.

- ethminer/MinerAux.h
- libethash-cuda/CUDAMiner.cpp
- libethash-cuda/CUDAMiner.h
It is prudent to make the re-evaluation of cuda search
results optional in host software. The default mode is the
legacy behavior.
Benefits:
- No one is caught by surprise inadvertantly flooding the
pool with invalid solutions due to overclocked GPU errors.
- The software eval is a necessary piece of overclock
tuning, again to avoid sending invalid solutions.
- Bypassing eval can be turned on for configurations known
to be stable. In that state, GPUs actually WILL always
yield valid solutions.
> Make cuda eval bypass optional

- libethash-cuda/CUDAMiner.cpp
- libethash-cuda/ethash_cuda_miner_kernel.h
These errors typically occur on overclocked
CUDA GPUs and are presently unrecovered.
They often result in a miner that appears
to be mining but is finding no shares.
These usually can be recovered with a miner
restart. Give the user an opportunity  to do so
via script by exiting on such errors.
> Exit on cuda run-time error

- libpoolprotocols/stratum/EthStratumClient.cpp
Setting m_running to false will cause the doStratum
solution stats loop to exit.
Ref: issue #700
> Prevent stratum disconnect from killing solution stats

- ethminer/MinerAux.h
- libpoolprotocols/PoolClient.h
- libpoolprotocols/PoolManager.h
- libpoolprotocols/getwork/EthGetworkClient.h
- libpoolprotocols/stratum/EthStratumClient.cpp
- libpoolprotocols/stratum/EthStratumClient.h
The m_running variable and associated isRunning method
is only set to false in stratum where it was actually
used incorrectly!
In my view, if a pool protocol client is instantiated then
by definition it is running. The m_connected and m_registered
variables are sufficient to manage the protocol state.
The termination of the doStratum loop was conditioned
by the client's isRunning state, which was only ever
inappropriately set to false on a disconnect.
The loop now will never terminate, which is a problem
for controlled shutdown. I believe the coming conversion
of stratum to a full fledged pool protocol client
will correct the problem.
git diff complains about missing terminating newlines...
> Get rid of unused or inconsistent protocol method

- ethminer/MinerAux.h
- libethash-cl/CLMiner.cpp
- libethash-cl/CLMiner_kernel_experimental.cl
- libethash-cl/CMakeLists.txt
As I understand this so called unstable kernel was
indeed faster and stable on some GPUs
> Rename alternate kernel to more representative name

- libpoolprotocols/stratum/EthStratumClient.cpp
- libpoolprotocols/stratum/EthStratumClient.h
Local `boost::asio::ip::tcp::resolver` instance was destroyed before the request is finished, resulting in "Operation cancelled" error.
> Fixes #624 and others.

- libethash-cl/CLMiner.cpp
- libethash-cl/CLMiner.h
- libethash-cl/CMakeLists.txt
- libethash-cuda/CMakeLists.txt
- libethash-cuda/CUDAMiner.cpp
- libethash-cuda/CUDAMiner.h
- libethcore/CMakeLists.txt
- libethcore/Farm.h
- libethcore/Miner.h
- libhwmon/wrapadl.cpp
- libhwmon/wrapadl.h
- libhwmon/wrapamdsysfs.cpp
- libhwmon/wrapamdsysfs.h
- libhwmon/wrapnvml.cpp
This should fix problems with ADL, which does not like using multiple instances of the driver interface. #541
I also changed the nvml wrapper to work without CUDA, so if you want to use nvidia with ocl and have access to HWMON you now can, without the need to compile with CUDA.
Possible also fixes some problems with mixed cards, but i'm not sure. or other hwmon problems. #540
I also had no time actually testing this, that much.
> Changed HWMON to init library only once.

- ethminer/MinerAux.h
- libethcore/Farm.h
- libpoolprotocols/PoolManager.cpp
- libpoolprotocols/stratum/EthStratumClient.cpp
- libpoolprotocols/stratum/EthStratumClient.h
* Adapted StartumClient to use PoolClient interface to work with PoolManager
* Deactivated stopping farm on "restartMiner" RPC command, which leaded to crashes/bugs. Needs a separate fix, see #744 and others. In fact, deactivated command alltogether
* Don't shutdown miner on disconnect, same as on restart miner, farm.stop is broken. But should be added back once farm.stop/pause  works again. see #734
* PoolManager now sets the active pool connection to farm.setPoolAddresses
* Does not contain a fix for ``-FS exit`` yet
> Reworked StratumClient to work with PoolManager

- libapicore/ApiServer.cpp
- libethcore/Farm.h
- libethcore/Miner.h
Hello,
I worked on the API method for getting the power usage, I created my output format as simple as I could:
{
"ethhashrate":"336745.9h/s",
"ethhashrates":["20692.1h/s","21007.2h/s","21007.2h/s","21007.2h/s","21112.3h/s","21322.3h/s","21427.4h/s","21217.3h/s","21217.3h/s","20482.1h/s","21322.3h/s","21112.3h/s","21112.3h/s","20692.1h/s","21217.3h/s","20797.2h/s"],
"ethinvalid":"0",
"ethpoolsw":"0",
"ethrejected":"0",
"ethshares":"2",
"fanpercentages":["66%","64%","70%","68%","66%","66%","74%","64%","70%","70%","66%","70%","70%","70%","70%","70%"],
"pooladdrs":"us1.ethermine.org:4444",
"powerusages":["73.6W","74.1W","74.6W","74.6W","74.2W","74.9W","74.6W","74.6W","74.8W","74.6W","74.4W","74.6W","74.7W","74.2W","73.6W","74.0W"],"runtime":"0","temperatures":["53C","52C","55C","54C","53C","5 …
> A simple JSON API format for supporting Power Usage

- ethminer/MinerAux.h
Allow the -HWMON parater to be specified without extra parameter.
> Provide backward compatibility with former -HWMON syntax

- libethash-cuda/dagger_shuffled.cuh
Give compiler better optimization opportunity
by combining two loops.
> Remove redundant loop from cuda GPU code

- .clang-format
This is a followup of #503 which reduces the size of the file ``.clang-format`` to its minimal version.
Additionally, the first patch corrects some inconsistencies by the usage of different version of clang. The new version requires clang 5+.
> Reduce size of .clang-format

- ethminer/main.cpp
- libdevcore/Log.cpp
- libethash-cl/CLMiner.cpp
- libethash-cuda/CUDAMiner.cpp
- libethash-cuda/CUDAMiner.h
Enable switch time logging by setting --verbosity
greater than 5.
> OpenCl and CUDA - Display consistent log output

- ethminer/MinerAux.h
- libethash-cl/CLMiner.cpp
- libethash-cl/CLMiner.h
- libethash-cuda/CUDAMiner.cpp
- libethash-cuda/CUDAMiner.h
- libethcore/Miner.cpp
- libethcore/Miner.h
You can now use --exit to shut down the miner whenever an error occurred.
Note, that this is not recommended, and only useful for people with additional software to restart the miner
https://github.com/ethereum-mining/ethminer/issues/97
> added --exit parameter to exit whenever an error occurred

- libpoolprotocols/PoolManager.cpp
This will take care of infinite retry loops without
fallback in the case such as with us1-etc.ethermine.org
currently. It connects but fails on read.
> Don't consider client connected till it gets a job.

- ethminer/MinerAux.h
- libpoolprotocols/CMakeLists.txt
- libpoolprotocols/stratum/EthStratumClient.cpp
- libpoolprotocols/stratum/EthStratumClient.h
ethermine.org starts testing SSL support for their pool.
This adds support for encrypted stratum pool connections.
Server to test with:
1) Valid ssl cert: stratum-ssl-test.ethermine.org:5555
2) SelfSigned: stratum-ssl-test.ethermine.org:6666
You need use ``--stratum-ssl``  to enable ssl for pool connections.
It should work for 1) but fail for 2) (certificate validation failed)
Optional options for the param:
* 0 = default, force tls1.2 connection
* 1 = allow any tls version
* 2 = disable certificate verification
> Stratum SSL/TLS Support

- ethminer/MinerAux.h
- libethash-cl/CLMiner.cpp
- libethash-cuda/CUDAMiner.cpp
- libethcore/Farm.h
- libethcore/Miner.h
- libhwmon/wrapadl.cpp
- libhwmon/wrapadl.h
- libhwmon/wrapamdsysfs.cpp
- libhwmon/wrapamdsysfs.h
- libhwmon/wraphelper.h
- libhwmon/wrapnvml.cpp
- libhwmon/wrapnvml.h
I managed to get my hashrate working for all the cards, I'm currently working on fixing hwinfo monitors which are not working for the AMD cards. Please refer to #725 last comments to see the problem and solution.
Please don't close the PR until I fix monitors.
> Mixed multiple AMD+NVIDIA fix

- ethminer/MinerAux.h
- libethash-cl/CLMiner.cpp
- libethash-cuda/CUDAMiner.cpp
- libethcore/Farm.h
- libpoolprotocols/PoolManager.cpp
- libpoolprotocols/PoolManager.h
- libpoolprotocols/stratum/EthStratumClient.cpp
- libpoolprotocols/stratum/EthStratumClient.h
* More fixes for farm.stop
* Re-enabled api event for miner restart
* On disconnect shutdown all mining to save wasted power
* Start worktimeout in stratum right after a successful connection. So if connection is successfull but something else failes and you never get work, this triggers a reconnect after the timeout is reached 
Disclaimer:
farm.stop()  still can cause driver resets, i modified my simulator to disconnect after a while but never had a driver reset with this test after 2h of simulating. But i had driver resets by stopping the miner, which should do the same so i do not know what causes the driver reset.
> Optimized farm.stop and worktimeout in stratum

- ethminer/MinerAux.h
Very tiny change in help. `--list-devices`can also use `-X`
"Should be combined with -G, -U, or -X flag"
> --list-devices -> add -X

- ethminer/MinerAux.h
Accessing reserved range of m_endpoints with operator[] produces undefined results and leads to segfault in some systems.
> Segfault by m_endpoints

- libpoolprotocols/PoolURI.cpp
- libpoolprotocols/PoolURI.h
The parser will correctly handle the @ sign in a nanopool
password if the @ is encoded as %40. All uri accessor functions
are equiped with a decoder such that the password will be
transmitted unencoded.
> Support nanopool password by allowing %40 substitution for @

- libethash-cuda/CMakeLists.txt
This resulted in Windows build warnings because it replaced `/W3` with `/w`.
Fixes #910.
> MSVC: remove `disable-warnings` from cuda switches.

- libpoolprotocols/PoolClient.h
- libpoolprotocols/PoolManager.h
- libpoolprotocols/getwork/EthGetworkClient.h
The headers already include `#pragma once` directives.
> Remove unneeded include guards.

- cmake/EthCompilerSettings.cmake
- libdevcore/Common.h
- libethash-cuda/CUDAMiner.h
* specify `_CRT_SECURE_NO_WARNINGS` instead of disabling C4996
* move preprocessor definitions to `add_definitions`
* remove no longer needed warnings suppressions
@chfast: this should be a lot safer than the first attempt; this time I double-checked and there's no hashrate change, only cleanup :)
> Clean up MSVC compiler options.

- libethash-cl/CLMiner.cpp
- libethash-cl/CLMiner.h
- libethash-cuda/CUDAMiner.cpp
- libethash-cuda/CUDAMiner.h
- libethcore/EthashAux.cpp
- libethcore/EthashAux.h
- libpoolprotocols/getwork/EthGetworkClient.cpp
- libpoolprotocols/stratum/EthStratumClient.cpp
- libpoolprotocols/testing/SimulateClient.cpp
The epoch number is needed anyway to build light cache. Still provide a helper toEpoch() to recreate the epoch number from seed hash.
> Use epoch number instead of seed hash

- libpoolprotocols/stratum/EthStratumClient.cpp
This sets the shared pointers for the sockets to null so that the
destructors of the sockets will get called when the reference count
is zero.  Without the fix there are situations where the sockets
appear to be alive after disconnection.
> make sure that connections are deleted on disconnect

- ethminer/MinerAux.h
- ethminer/main.cpp
The git hash is now included in `buildinfo.project_version`.
> Clean up ethminer --version

- ethminer/MinerAux.h
- libethash-cl/CLMiner.cpp
- libethash-cl/CLMiner.h
- libethash-cl/CLMiner_kernel_experimental.cl
- libethash-cl/CLMiner_kernel_stable.cl
- libethash-cuda/CUDAMiner.cpp
- libethash-cuda/CUDAMiner.h
- libethcore/Miner.cpp
- libethcore/Miner.h
- Rename -cuda-noeval option to --noeval since it can now apply to
both Cuda and OpenCl.
- Add support for using GPU mix hash result when noeval is set in
CLMiner.
- Modify experimental opencl kernel to return mix hash on solution
found.
- Modify stable opencl kernel to return mix hash on solution
found.
- Move global s_noval bool to common miner.cpp
> No eval for OpenCL - One last thing on my ethminer todo list.

- ethminer/MinerAux.h
With new uri schema, no default connection exists and simulation broke.
This adds a new dummy connection if in Simulation Mode.
This fixes #1018
> fix for #1018

- ethminer/MinerAux.h
- libpoolprotocols/stratum/EthStratumClient.cpp
- libpoolprotocols/stratum/EthStratumClient.h
Add --response-timeout as new cli argument to allow tuning on shared
network connections.
> Response timeout as configurable CLI argument

- libethash-cl/CLMiner.cpp
[improving output/behavior of CLMiner::configureGPU() if a subset of the available GPUs is selected]
What I think CLMiner::configureGPU() intends to do: 
Check for each OpenCL device [GPU] that is has sufficient Memory in order to contain the DAG file.
What it currently does:
It checks if the first (and only the first) OpenCL device in the given platform has sufficient memory.
It ignores any GPU selection settings. If the first device does not fulfill the memory requirement, it quits.
What it does after including my change:
It checks every OpenCL device in the given platform, and only quits if none of them fulfill the memory requirement.
> improving CLMiner::configureGPU() if a subset of the available GPUs is selected

- ethminer/MinerAux.h
- libethash-cl/CLMiner.cpp
- libethash-cl/CLMiner.h
The default parameters are ok for the 480, but less so for 460, and
470. The global work size is adjusted up or down depending on the
number of GPU compute units, allowing for better optimization of
rigs with mixed AMD GPU types.
> For AMD. Adjust global work size according to # of compute units.

- CHANGELOG.md
- CMakeLists.txt
> Disable Visual Studio Debug configuration

- ethminer/MinerAux.h
- libethash-cl/CLMiner.cpp
- libethash-cuda/CUDAMiner.cpp
- libethcore/Farm.h
- libethcore/Miner.cpp
- libethcore/Miner.h
As we're getting summer here:
To be sure not to burn the GPUs the miner stops mining on a GPU
if a specific temperature (--tstop) is reached.
After cooling down and reaching --tstart temperature (default 40)
mining will be (re)started on the GPU.
> Add --tstop and --tstart option preventing GPU overheating.

- libethash-cuda/CUDAMiner.cpp
Exit check was in the wrong place, leaving streams unsynchronized.
> Work loop minor bug fix

- CHANGELOG.md
- libpoolprotocols/stratum/EthStratumClient.cpp
- libpoolprotocols/stratum/EthStratumClient.h
nicehash will periodically adjust difficulty, sending it as
a float value to be converted to 32 byte target. There is no
need to do the conversion with every job.
> Stratum nicehash. Avoid recalculating target with every job.

- CHANGELOG.md
- libpoolprotocols/PoolManager.cpp
- libpoolprotocols/PoolManager.h
There are two known cases where pools will send duplicate jobs
leading to rejected shares.
1 - Ethermine will occasionally incorrectly send a duplicate job.
job A
job B
job C
job B <- undexpected dup.
job D
This occurs for reason unknown (pool bug?) causing the miner to
restart work on job B and finding the same solutions as the 1st
time through, these then rejected as duplicates.
Furthermore, this prevents any further results which might have
been found for job C.
2 - Protocol startum2 (nicehash) resends job after difficulty
change.
job A
job B
new diff
job B <- incorrectly restarts job B.
Some nicehash pools (counfoundry) resend the previous job after
sending a difficulty update notification. Causes the same problem
as in case 1.
Solution.
Keep a list of for last 4 jobs and drop any …
> Work around pool bugs (drop duplicate jobs)

- libpoolprotocols/PoolManager.cpp
Due to recent changes in workloop for PoolManager, stop mining may not
be invoked when program exits due to signal or CTRL-C
> Invoke stop mining.

- ethminer/main.cpp
- libdevcore/Log.cpp
- libdevcore/Log.h
- libethash-cl/CLMiner.cpp
- libethash-cuda/CUDAMiner.cpp
- libpoolprotocols/PoolManager.cpp
- Simplifiy code. There's no point in setting the color to black then
printing someting on a black background. Might as well just use blanks.
- Since we don't enable and disable log channels, there's no need
for a channel map or its protective mutex.
- Prefer cmd line parameters to env. variables. Add --nocolor, --syslog options
- Rename log global variables appropriately.
- Shorten log message ids to 2 characters.
- Remove unnecesary color setting when in syslog mode
> More log logic cleanup

- cmake/EthCompilerSettings.cmake
This is the default for the SDK we use.
Not sure if we should set it at all...
PS. The binaries already don't run on XP anyway; the default Windows Subsystem version is 6.0 (Vista).
> Change _WIN32_WINNT to Vista.

- CHANGELOG.md
- ethminer/main.cpp
- libpoolprotocols/getwork/EthGetworkClient.cpp
- libpoolprotocols/getwork/EthGetworkClient.h
Addresses #1213
- Solution submit is immediate upon arrival and is no influenced by --farm-recheck value
- Submission of hashrate is conditional
- Renamed m_report_stratum_hashrate to m_report_hashrate as it's valid for both modes
Now even sligtly higher --farm-recheck values may be applied to mitigate overhead.
> Critical amendment to GetWorkClient

- libapicore/ApiServer.cpp
- libapicore/ApiServer.h
- libpoolprotocols/stratum/EthStratumClient.cpp
- libpoolprotocols/stratum/EthStratumClient.h
> Small fixes

- ethminer/main.cpp
- libapicore/ApiServer.cpp
> Correction for late binding to local listener on api server

- CHANGELOG.md
- ethminer/main.cpp
- libapicore/ApiServer.cpp
- libapicore/ApiServer.h
Will help protect exposure of API port to the Web
> Implementation of basic API authentication

- API_DOCUMENTATION.md
- POOL_EXAMPLES_ETH.md
- README.md
- appveyor.yml
* fix some typos
* remove `host=x64` from the cmake command; we already specify `Win64` in the generator command.
* add an example Windows script to build ethminer
* assorted Markdown tweaks
> Tweak docs

- libdevcore/Log.cpp
- libdevcore/Log.h
- Specifically, large numbers are hard to parse.
> Make log values more readable using locale specific formatting

- ethminer/main.cpp
- libethcore/Farm.h
- libethcore/Miner.h
- libpoolprotocols/PoolManager.cpp
- No need to count stale rejects separately.
- Use minimal spacing... line gets very long for multi GPU
- Other than accepted, only display non zero solution stats.
> Shorten mining progress logs.

- libapicore/ApiServer.cpp
Adding possibility to check ispaused if hashrate on a card drops to 0.
> RPC API miner_getstathr: Add "ispaused" information into response.

- CHANGELOG.md
- docs/API_DOCUMENTATION.md
Update documentation to match change 6df515edaec6ff1604ddee579851751b0b5329cd .
> Add info about modified response of miner_getstathr API call.

- CHANGELOG.md
- docs/API_DOCUMENTATION.md
- libapicore/ApiServer.cpp
- libapicore/httpServer.cpp
- libethcore/Miner.h
API version responses as requested by @AndreaLanfranchi at PR #1299.
Use same version number for html site.
> Different small changes

- libethcore/Miner.h
- std::atomic_uint64_t is not defined in older versions of gcc
> std::atomic_uint64_t not defined

- CHANGELOG.md
- libpoolprotocols/PoolManager.cpp
- libpoolprotocols/PoolURI.h
- libpoolprotocols/stratum/EthStratumClient.cpp
- libpoolprotocols/stratum/EthStratumClient.h
Eliminates the hassle of knowing in advance which is the stratum mode implemented by the pool. No more stratum/1/2+tcp:// but only stratum+tcp://
Added support for invalid connections. Whenever a connection cannot be established due to login errors (invalid worker or bad address) it's marked as Unrecoverable and won't be used again.
> Stratum mode autodetection

- libpoolprotocols/PoolClient.h
- libpoolprotocols/stratum/EthStratumClient.cpp
As for stratum autodetection a new issue  emerged in case pool's endpoint refuses connection since the very first. This PR amends it.
> Prevent never-ending loop due to stratum mode autodetection

- docs/API_DOCUMENTATION.md
- ethminer/main.cpp
- libapicore/ApiServer.cpp
- libapicore/ApiServer.h
- libapicore/httpServer.cpp
- libapicore/httpServer.h
this allows listening to only a specific network address, for example, this allows ethminer to only listen for connections from localhost, or only listen to a VPN/secure network, instead listening in on all available networks. i also replaced `--api-port`  in the documentation  with `--api-bind`,  as this kindof supersedes it.
> add --api-bind and --http-bind parameters

- ethminer/main.cpp
- libethash-cl/CLMiner.cpp
- libethash-cl/CLMiner.h
Since zawawawa open sourced his kernels, I added a binary loader to load them for AMD cards based on architecture and local work size. This patch adds another value for the option kernel option i.e. ```--cl-kernel 2``` which loads the binary kernels from ```./kernels/```. There's also ```--cl-iterations``` which controls a parameter with the kernel. Kernels can be found [here](https://github.com/goobur/ethash-kernels) although they're still experimental.
> Binary loader for Zawawawa's kernels

- libethash-cl/CLMiner.cpp
Not sure why:
m_searchKernel.setArg(5, ~0UL);  // Pass this to stop the compiler unrolling the loops.
if(s_clKernelName == CLKernelName::Binary && loadedBinary) {
m_searchKernel.setArg(6, uint32_t(dagNumItems));
m_searchKernel.setArg(7, uint32_t(s_kernelIterations));  // Number of iterations
}
would be any different from:
if(s_clKernelName == CLKernelName::Binary && loadedBinary) {
m_searchKernel.setArg(5, ~0UL);  // Pass this to stop the compiler unrolling the loops.
m_searchKernel.setArg(6, uint32_t(dagNumItems));
m_searchKernel.setArg(7, uint32_t(s_kernelIterations));  // Number of iterations
}else {
m_searchKernel.setArg(5, ~0u);  // Pass this to stop the compiler unrolling the loops.
}
But for some reason the former completely breaks CLMiner!!!
Wait... I see... one is uint32 the …
> Fix broken opencl miner

- libpoolprotocols/PoolManager.cpp
- libpoolprotocols/PoolManager.h
If a connection is changed via API call 'miner_setactiveconnection'
ethminer displays info that it disconnects from the "new" host.
Fixing this - display the correct host in the disconnect message.
> Correct disconnect message.

- libapicore/ApiServer.cpp
- libapicore/httpServer.cpp
- libpoolprotocols/stratum/EthStratumClient.cpp
Use "ethminer-" instead "ethminer " as version prefix within stratum communication.
@AndreaLanfranchi : Request a review
@chfast : Could we get a function in the ethminer_get_buildinfo()->xxx to get a full qualified name/version info ? (We're currently using the "version" in stratum, api and html and always have to prefix "ethminer-")
> Stratum: Correct miner version

- ethminer/main.cpp
- libethash-cuda/CUDAMiner.cpp
When accessing CUDAMiner, CUDAMiner::getNumDevices() is
called which can cause an exception.
Catch the exception, display the error message and exit.
Found this problem while searching solution for ISSUE #1378 - maybe this solves the problem.
> Fix CUDA driver version check.

- CHANGELOG.md
- docs/API_DOCUMENTATION.md
- libapicore/ApiServer.cpp
To identify problems on a running instance it is helpful to change the verbosity level without restarting.
This commit allows the change of verbosity via an API call.
> Api: Add miner_setverbosity().

- ethminer/main.cpp
- libpoolprotocols/PoolClient.h
- libpoolprotocols/PoolManager.cpp
- libpoolprotocols/stratum/EthStratumClient.cpp
* --farm-retries allows 0
* PoolClient receives a pointer to URI instead of a reference
* PoolClient method unsetConnection releases the pointer
* PoolManager gets rid of Unrecoverable connections with a copy of vector (could not make vector.erase to function)
* EthStratumClient now marks as unrecoverable connections where mining.authorize is not succesful
Amends #1405
> Consistent behavior of -P exit

- libethash-cl/CLMiner.cpp
- libethash-cl/CLMiner.h
- ethminer leaks context with each new epoch
> Make sure old opencl context is deleted before allocating new.

- libpoolprotocols/PoolManager.cpp
- libpoolprotocols/stratum/EthStratumClient.cpp
- libpoolprotocols/stratum/EthStratumClient.h
Detecting proper stratum mode is a try-and-error process.
Unfortunately there's not a unified standard implemented by pools to handle errors.
This PR enforces a standard on ethminer's side by :
1. Connect socket. If error ... try next available endpoint.
2. Send out the method under test
3. Waiting for any event which imply test failure. If none go to step 6
4. Failing events may be : explicit trasmission of json message with error and / or connection drop on pool's side and or any kind of timeout.
5. Disconnect socket connection and reconnect. Goto point 2.
6. Mark the found stratum mode as confirmed on connection object.
If, during the connection rotation due to failovers, an already used connection is set to current **and** it has stratum protocol marked as confirmed the autodetection …
> Stratum auto-detection extensive logic review

- ethminer/main.cpp
Remove compiler warning [warning C4101: 'ex': unreferenced local variable (see Line 982)](https://ci.appveyor.com/project/ethereum-mining/ethminer/build/1937#L982)
> Remove unused variable.

- libethcore/Farm.h
- libpoolprotocols/PoolClient.h
- libpoolprotocols/PoolManager.cpp
- libpoolprotocols/getwork/EthGetworkClient.cpp
- libpoolprotocols/stratum/EthStratumClient.cpp
- libpoolprotocols/testing/SimulateClient.cpp
- We should not resubmit the current job upon receiving a new
difficulty or extranonce from stratum 2. Theses changes only
apply to the next job received.
> Fix false duplicate jobs when using stratum 2

- libethash-cl/CLMiner.cpp
Fixes the problem described here: #1446 
It seems osx does not like statics at all and if its an array it does not like const too.
I also tried keeping the const and using an reference on ``enqueueWriteBuffer`` for zerox3 but that did not work either.
> osx crash fix on opencl

- CMakeLists.txt
- ethminer/main.cpp
- libapicore/ApiServer.cpp
- libpoolprotocols/CMakeLists.txt
- libpoolprotocols/PoolManager.cpp
- libpoolprotocols/PoolURI.cpp
- libpoolprotocols/PoolURI.h
- Third party support is useful when it works, but...
- Replace buggy network-uri with in-house URI parser.
> Remove dependency on buggy version of network-uri package

- libethash-cl/CLMiner.cpp
- libethash-cuda/CUDAMiner.cpp
- libethcore/Miner.h
Use steady non-adjustable clock for time laps measurement.
#626
> Use steady_clock

- libpoolprotocols/stratum/EthStratumClient.cpp
After removal of dup check headerHash becomes unused
> Remove unused variable

- ethminer/main.cpp
This will fix issues on build running the `-DETHDBUS=ON` flag
> moved dbusint include to after minelog definition

- libpoolprotocols/PoolManager.cpp
- libpoolprotocols/PoolManager.h
None of these are duplicates!!!
X 14:17:32 stratum  **Duplicate job #99d1de93… discarded**
i 14:17:36 stratum  Job: #447e59f9… us1-etc.ethermine.org [54.177.207.188:5555]
X 14:17:36 stratum  **Duplicate job #447e59f9… discarded**
i 14:17:41 stratum  Job: #84034167… us1-etc.ethermine.org [54.177.207.188:5555]
X 14:17:41 stratum  **Duplicate job #84034167… discarded**
i 14:17:42 cuda-1   Solution: 0xe139927e7a7120fa
i 14:17:42 stratum  **Accepted  73 ms. us1-etc.ethermine.org [54.177.207.188:5555]
i 14:17:53 cuda-3   Solution: 0xe139947e8a30fb28
i 14:17:53 stratum  **Accepted  73 ms. us1-etc.ethermine.org [54.177.207.188:5555]
i 14:18:11 stratum  Job: #f8e8f361… us1-etc.ethermine.org [54.177.207.188:5555]
X 14:18:11 stratum  **Duplicate job #f8e8f361… discarded**
i 14:18:25 cuda-0 …
> Remove duplicate job test... does more harm than good!

- libpoolprotocols/PoolManager.cpp
When setting new active connection by API call shutdown mining as we do with regular connection switching due to failover
> Stop mining on API connection change

- ethminer/main.cpp
- libpoolprotocols/PoolURI.cpp
Due to the implementation of stratum autodetection there is no need to specify different stratum flavours.
> Simplify CLI arguments

- .travis.yml
- scripts/install-cuda-ubuntu1604.sh
This allows using older Nvidia drivers without any performance lost.
> CI: Downgrade CUDA SDK to 9.1

- ethminer/main.cpp
- libapicore/ApiServer.cpp
- libapicore/httpServer.cpp
- libethash-cuda/CUDAMiner.cpp
- libethash-cuda/ethash_cuda_miner_kernel.h
- libethcore/Farm.h
- libethcore/Miner.h
Data collecting (hashing and hw info) lives in it's own timer (5 seconds) not influenced by `--display-interval` or by the number of calls issued via API.
Hashing average is, as said, on last 5 seconds which gives (IMHO) a better feeling of hashing lost on frequent job changes issued by pool.
All process has been greatly simplified.
Addresses #1478
> Farm automation

- docs/POOL_EXAMPLES_ETH.md
- ethminer/main.cpp
- libpoolprotocols/PoolURI.cpp
- libpoolprotocols/stratum/EthStratumClient.cpp
Sets some basic aliases for job retrieval mode:
* getwork:// default scheme for http mode. (http:// is also kept)
* stratum:// default scheme for tcp mode. This also endorses stratum auto-detection
* stratums:// default scheme for tcp mode **secure**. This also endorses stratum auto-detection
* stratumss:// default scheme for tcp mode **secure with TLS validation**. This also endorses stratum auto-detection
Older schemes are preserved for backward compatibility and, if set, do not activate stratum autodection. So when -P argument is valued : 
* `stratum+tcp://` means the user wants to stick to stratum mode 
* `stratum1+tcp://` means the user wants to stick to ethproxy compatible mode 
* `stratum2+tcp://` means the user wants to stick to nicehash mode 
All those previous also keep …
> Auto stratum

- libapicore/ApiServer.cpp
If -HWMON 1 is not set then API call miner_getstathr segfaults to access an empty vector
> Check minerMonitors.size()

- libethash-cl/CLMiner.cpp
- libethash-cuda/CUDAMiner.cpp
- libethcore/Miner.cpp
- libethcore/Miner.h
- These functions were inlined for convenience, to avoid
multiple declaration errors. This is not a good reason to
inline a function.
- None of these are used in performance critical areas
> Move function bodies (non methods) to cpp.

- ethminer/main.cpp
- libethcore/Miner.cpp
- libethcore/Miner.h
- Restore miner hash rate smoothing
- SMA does better job than exponential averaging
> Apply simple moving average over 10 hash rate samples

- libapicore/ApiServer.cpp
Now p.minerMonitors.size() can also be 0 if  --HWMON option was not supplied.
> NFC: Correct an assertion condition.

- libethcore/Farm.h
- libpoolprotocols/PoolManager.cpp
As the DAG only depends on the epoch we don't have to destroy all mining
threads and delete the DAG if we change a connection.
Keep the mining threads alive but suspend them while connection change.
If the new connection has a different epoch DAG will be generated when mining is resumed.
This should result in faster pool failover switches and faster connection
switches via API as the DAG will be only generated if we get a different epoch.
> Generate DAG only on change - even when switching connection

- ethminer/main.cpp
- libapicore/ApiServer.cpp
- libapicore/httpServer.cpp
- libethash-cl/CLMiner.cpp
- libethash-cl/CLMiner.h
- libethash-cuda/CUDAMiner.cpp
- libethash-cuda/CUDAMiner.h
- libethcore/Farm.h
- libethcore/Miner.cpp
- libethcore/Miner.h
- libpoolprotocols/PoolManager.cpp
Instead of calculating hash rate at the collector's polling pass,
calculate the current hash rate of the last n batches in real
time. N is chosen to provide relatively long (.5 secs) GPU search
loop driven calculation interval. For AMD n=1 works well, and for
Nvidia which uses short batches N=128.
This PR does not affect the collector thread or the display loop,
but the collector thread may not be needed.
> A method for nearly instantaneous hash rate measurements.

- libethcore/Miner.cpp
- libethcore/Miner.h
- Delete unnecessarily maintained variable
- Allow the compiler the option to inline time
critical method.
> Minor optimization and cleanup

- ethminer/main.cpp
- libpoolprotocols/PoolClient.h
- libpoolprotocols/PoolManager.cpp
- libpoolprotocols/PoolManager.h
- libpoolprotocols/getwork/EthGetworkClient.cpp
- libpoolprotocols/stratum/EthStratumClient.cpp
- libpoolprotocols/stratum/EthStratumClient.h
- libpoolprotocols/testing/SimulateClient.cpp
As described in #1503 there might be cases when timeouts are not triggered.
These changes include :
* Move the timing section at transport level
* Keep track of a queue of awaited responses
* Process response delays FIFO style and advance always the older
* Remove several deadline timers with their initializations and callback routines.
* Wrap all timings measurement in a single workloop_timer_elapsed routine which ticks every second
Still not perfect as it may trigger timeouts slightly late (up to 1 second additional delay) but on the other hand we get a correct sequence of response times
> Rearrange Stratum Timings

- ethminer/main.cpp
- libapicore/ApiServer.cpp
- libapicore/ApiServer.h
- libethash-cl/CLMiner.cpp
- libethash-cuda/CUDAMiner.cpp
- libethcore/Farm.h
- libethcore/Miner.h
- libpoolprotocols/PoolClient.h
- libpoolprotocols/PoolManager.cpp
- libpoolprotocols/PoolManager.h
- libpoolprotocols/getwork/EthGetworkClient.cpp
- libpoolprotocols/getwork/EthGetworkClient.h
- libpoolprotocols/stratum/EthStratumClient.cpp
- libpoolprotocols/stratum/EthStratumClient.h
- libpoolprotocols/testing/SimulateClient.cpp
- libpoolprotocols/testing/SimulateClient.h
* Introduce solutions per gpu
* @AndreaLanfranchi : I submit solutions with an id of (10 + miner_index) so I can map the response back to the corresponding gpu.
* @chfast : Don't know if coverty likes the changes as the SolutionStat is written by Poolmanager and read by API thread. Any suggestions ?
* Keep value of last received difficulty
* Introduce API call miner_getstatdetail()
* Use the infos "solutions per gpu" and last received difficulty
* API interface inspired by [Andrea's comment](https://github.com/ethereum-mining/ethminer/pull/1232#discussion_r193995891) of #1232 (goto  `AndreaLanfranchi requested changes on Jun 8`  and show Outdated)
* Think API interface is not ready being official documented
> Introduce solutions per gpu

- CHANGELOG.md
- ethminer/main.cpp
- libapicore/ApiServer.cpp
- libdevcore/Log.cpp
- libdevcore/Log.h
- libethash-cl/CLMiner.cpp
- libethash-cuda/CUDAMiner.cpp
- libethcore/Miner.h
- libpoolprotocols/stratum/EthStratumClient.cpp
The verbosity level was intended to indicate severity of
a log entry. Over time we've used it inappropriately to
enable various log options. This has led us to a situation
where it is impossible to enable some options without
also enabling others.
This changes the global verbosity setting to be a set of
bits, each indicating if a log feature is enabled.
The following choices are defined and spelled out in the
help.
#define LOG_SWITCH_TIME 1
#define LOG_JSON 2
#define LOG_PER_GPU 4
#define LOG_DEBUG 8
Any combination of the sum of these options (0-15) is allowed.
> Provide more granular control of logging options

- libethash-cl/CLMiner.cpp
- libethash-cl/CLMiner.h
- libethash-cuda/CUDAMiner.cpp
- libethash-cuda/CUDAMiner.h
- libethcore/Farm.h
- libethcore/Miner.h
- The hardware data collector is invoked every 5 seconds.
there is no need for hash rates to be calculated more
frequently. Let the collector trigger hash rate calculation.
- This has the added advantage of decoupling the sampling
interval from group and multiplier parameters.
> Normalize hash rate sampling interval

- libethash-cuda/CUDAMiner.cpp
- libethash-cuda/CUDAMiner.h
- libethash-cuda/ethash_cuda_miner_kernel.cu
- libethash-cuda/ethash_cuda_miner_kernel.h
- Capitalize type names of search_results structs
- Use references rather than pointers
- Scope variables
> Cleanup cuda miner

- libethash-cuda/CUDAMiner.cpp
- libethash-cuda/CUDAMiner.h
- libethash-cuda/ethash_cuda_miner_kernel.h
It makes more sense to do non critical things like calculating
hash rates and submitting solutions while the CPU is idle instead
of when the GPU is idle. But the added complexity could not
be justified based on analysis.
That analysis was based on submit time measurements of less than
1 microsecond, which is indeed the case when using the --noeval
option. However software eval is on by default. Recalculating
the mix hash in software takes 4-5 milliseconds on a reasonably
fast CPU. This imposes a much more substantial delay restarting
a stream, and has a cascading effect delaying all other streams.
This approach is not much different from previous implementations.
It merely saves all found solutions till all cuda streams searches
have been restarted and are not waiting for the CPU. Once …
> CUDA search loop optimization - pass 2!

- ethminer/main.cpp
- libapicore/ApiServer.cpp
- libapicore/ApiServer.h
- libapicore/httpServer.cpp
- libapicore/httpServer.h
- libethcore/Farm.h
- libpoolprotocols/PoolManager.cpp
- libpoolprotocols/PoolManager.h
- libpoolprotocols/stratum/EthStratumClient.cpp
- libpoolprotocols/stratum/EthStratumClient.h
The io_service, farm, and pool manager instances are
frequently used global objects. There is a single
instance of each.
Avoid a lot of parameter passing by accessing these
objects via global reference or pointer.
> Use singletons to access global objects

- ethminer/main.cpp
To use less cpu ethminer slept always for two seconds till
display-interval was reached or exceeded.
This commit corrects the handling of display interval.
Fixes also #1589
> Correct handling of --display-interval.

- ethminer/main.cpp
To use less cpu ethminer slept always for two seconds till
display-interval was reached or exceeded.
This commit corrects the handling of display interval.
Cherry-pick of 75f43e8d05b340d96c1b271920c83be0cca33d6a (#1591)
> Correct handling of --display-interval. (Cherry pick for v0.16.1)

- docs/API_DOCUMENTATION.md
- libapicore/ApiServer.cpp
- libapicore/ApiServer.h
- libethcore/Farm.h
- libethcore/Miner.h
Change times to seconds.
Add 'lastupdate' to global miner share info.
Set lastupdate initially to time when farm got launched.
This commit addresses a little bit of issue #1603.
> API: miner_getstatdetail(). Several changes.

- ethminer/main.cpp
- libpoolprotocols/stratum/EthStratumClient.cpp
- libpoolprotocols/stratum/EthStratumClient.h
As per #1629 the option to disable verification chain for certificates might be useful when used in controlled environments with self-signed certificates.
In any other case this should be considered a bad practice.
The option is enabled only by env variable and the absence of a CLI argument is expressly meant.
> Restores option to disable certificate validation

- libpoolprotocols/stratum/EthStratumClient.cpp
- libpoolprotocols/stratum/EthStratumClient.h
Referring to issue #1654
Stronger verification of the datastream received from socket. Also provide the possibility a single trasmission may include more than one message.
**Pass Json message for processing by value, not by reference as it may change during other async operations.**
> Proper buffer processing from async_read_until

- libpoolprotocols/stratum/EthStratumClient.cpp
- libpoolprotocols/stratum/EthStratumClient.h
This is an alternative to #1663 by @jean-m-cyr 
Main differences :
- it does not require a new thread. Keeps async model instead of a thread which sends sync
- stores the messages in queue as strings instead of json objects
- if pending queue has more than one message multiple lines are packed in a single transmission
Added some cosmetics for output json messages (single line) when logging option is set.
> Possible double send fix (alternative)

- libpoolprotocols/PoolURI.cpp
- libpoolprotocols/PoolURI.h
- libpoolprotocols/stratum/EthStratumClient.cpp
As we split username and workername by "." we have to do it before
an urlDecode() is called as otherwise it is not clear which part is
username and which is workername.
Previous this commit:
-P username%2e246891.rigname%2e01:x@HOST:PORT
Username = username, Workername = 246891.rigname.01
-P username%2erigname:x@HOST:PORT
Username = username, Workername = rigname
With this commit
-P username%2e246891.rigname%2e01:x@HOST:PORT
Username = username.246891, Workername = rigname.01
-P username%2erigname:x@HOST:PORT
Username = username.rigname, Workername =
So this commit breaks a syntax of
username%2erigname:x@HOST:PORT
as now this results in a
Username = username.rigname
against previous
Username = username, Workername = rigname
This commit should fix …
> Allow passing "." as username or workername using %2e.

- .clang-tidy
I enabled some groups of clang-tidy checks that I think make sense for a start. But there are a lots of warnings to fix.
Usage:
```
cmake -DCMAKE_CXX_CLANG_TIDY=clang-tidy .
```
> Add clang-tidy config

- libdevcore/Log.cpp
- clog and cout are buffered, cerr is not. Use clog instead of cerr.
> Simplify log logic

- libpoolprotocols/stratum/EthStratumClient.cpp
If m_current.block is filled and connection is switched to
another host and protocol, the last received blocknumber remains in
the m_current.block which is wrong (in following we get a wrong epoch).
This commit sets m_current.block by default to -1.
Also validate that the received block number is in a valid range.
> Initialize blocknumber when new job arrives.

- ethminer/main.cpp
- libapicore/ApiServer.cpp
- libpoolprotocols/PoolURI.cpp
- libpoolprotocols/PoolURI.h
- libpoolprotocols/stratum/EthStratumClient.cpp
- libpoolprotocols/stratum/EthStratumClient.h
Uri parsing now leverages regex.
Mandatory conventions are :
- a dot (`.`) marks the delimiter for Workername
- a column (`:`) marks the delimiter for Password
If User and/or Worker and/or Password contains any character that would impair uri parsing (namely `.` `:` `@` `?` or `#`) that string **MUST** be enclosed in backticks (ASCII 96).
Addressing https://github.com/ethereum-mining/ethminer/issues/1687
it's now possible to write
```
./ethminer -U -P stratum1+tcp://`username.246891`.rigname:x@eu-01.miningrigrentals.com:3344
```
Other possibilities
```
./ethminer -U -P stratum1+tcp://`johndoe@gmail.com`.`rigname:01`:x@eu-01.miningrigrentals.com:3344
```
**Note : in linux bash the backtick has the meaning of evaluation of expression thus it has to be further escaped with a backslash in …
> Modified URI Parsing (Username / WorkerName / Password)

- libethash-cuda/keccak.cuh
* asm optimziation using lop3 (less ptx-level instructions)
* use ROL8/ROR8 for some cases (byteperm is faster when rolling a multiple of 8 [2])
ptx-level output lines counted by simple `wc -l` command
(compiled  using `nvcc .... --ptxas-options="-v -O3" --ptx out.ptx ethash_cuda_miner_kernel.cu`)
nvcc option | original | inline asm | difference
--------|----------|------------|--------
`-gencode=arch=compute_61,code="sm_61,compute_61"` | 22025 | 21278 | -747 lines
(fewer ptx-level instructions more likely to reduce power consumption.)
[1]: lop3 - https://github.com/tpruvot/ccminer/blob/windows/Algo256/cuda_keccak256.cu#L50
[2]: ROL8/ROR8 - https://github.com/KlausT/ccminer/commit/cc61a351a70982c25a5702cca195647c6385bb95#diff-2508b8baaae67328e6d515653bb3e94d
> inline asm optimizations

- libpoolprotocols/PoolManager.cpp
- reduce log output by only displaying port number once per log line.
> Log line displays port number twice

- .travis.yml
- appveyor.yml
- scripts/install-cuda-ubuntu1604.sh
* fixed scripts/install-cuda-ubuntu1604.sh script to support cuda-8, cuda-9, cuda-10
* make scripts/install-* more potable
* a travis entry added to check cuda-8
* osx cuda-9.1 build added
Please see https://github.com/bytedeco/javacpp-presets/blob/master/ci/install-travis.sh#L271-L283
* appveyor fix for cuda-8, cuda-9.1 etc.
- download compiler from the official nvidia site.
- extract compiler only from the downloaded file using 7z. like as `7z foobar.exe -oC:\CUDA nvcc/*` and rename `C:\CUDA\nvcc` to `C:\CUDA\v9.1`
- use cuda-9.1 instead of cuda-9.0
- cuda-8.0 build added.
> travis fix to check cuda-8 support

- libpoolprotocols/PoolURI.cpp
With commit 9cbe1a14f59930e2c84167b64a441708e70a355e we lost
escaping special chacters within the pool connection using "%".
(Re)add that functionality so behaviour matches the
documentation added with #1743.
> (Re)add url_decode() to URI parser.

- libethash-cuda/keccak.cuh
reduced `vectorize()` (`mov.b64` ptx instruction) using `__constant__ uint2`
about ~30 `mov.b64` ptx instructions reduced.
for my P106-100 (6G samsung)
P106-100(6G) | `ethminer -U -M 50000`
---------|--------
original | min/mean/max: 24,034,424/24,040,047/**24,043,364** H/s
fixed  | min/mean/max: 24,037,682/24,040,596/**24,043,498** H/s
(almost no difference but small improvement)
> use uint2 const to reduce vectorize()/mov.b64

- libethash-cuda/ethash_cuda_miner_kernel_globals.h
- libethash-cuda/keccak.cuh
speed up `ethash_calculate_dag_item()` using `__ldg()`
P106-100(6G) | `ethminer/ethminer-fixed -U -M 1000000`
---------|---------
original | Generated DAG + Light in **6,102 ms**. 4.66 GB left.
fixed | Generated DAG + Light in **5,648 ms**. 4.66 GB left.
> load dag using __ldg()

- libethash-cl/CLMiner.h
Default CL Local Work Size is 192 which is not a power of 2.
Valid values are 32 64 128 256
Amends #1740
> Wrong default CL Local Work Size

- libhwmon/wrapnvml.cpp
Fixes HWMON report on Fedora and RHEL.
As discovered recently some RPM based distributions like Fedora and RHEL don't do symlink of libnvidia-ml.so, instead use libnvidia-ml.so.1. Ubuntu and other distributions already have that symlink and should not be affected.
> Rename HWMON dependency from libnvidia-ml.so to libnvidia-ml.so.1

- docs/POOL_EXAMPLES_ETH.md
More clarification about usage of `%` in Windows environments.
> Pool samples patch

- libhwmon/wrapnvml.cpp
Latest windows nvidia drivers do not ship opencl drivers with them anymore. Which causes hwmon to crash enumerating ocl platforms.
This PR is against 0.17, but i can change that if needed.
Resolves #1841
> Fix crash issue on latest nvidia windows drivers

- libapicore/ApiServer.cpp
Hi,
Calling API method `miner_shuffle` actually changes state and therefore is a write action. However, the  implementation fails to check if the miner is in readonly mode for `miner_shuffle` and would therefore allow to bypass this restriction.
according to the spec `miner_shuffle` is [write protected](https://github.com/ethereum-mining/ethminer/blob/master/docs/API_DOCUMENTATION.md) which is not the case.
worst case is probably someone constantly calling shuffle to interfere and severely degrade the miners performance. It is unclear to me if this would also lead to a DoS but could be the case.
* the API interface is written under the assumption that it will never be publicly available. whether this assumption reflects the real-world use of ethminers API is unclear. It therefore poses …
> security: adding write check to miner_shuffle to match the API_DOC spec

- ethminer/CMakeLists.txt
Hi,
cloned the repo, follow `doc/BUILD.md` to build ethminer. kept getting a linker error when building ethminer. found out that hunter wasn't linking it with `boost:thread`. This PR fixes the build.
cheers,
tin
os: ubuntu 18.10 docker. same issues on macos native (w/o any hashing support)
```
root@3257034f0e49:/tmp/project/build# cmake .. -DETHASHCL=OFF -DETHASHCUDA=OFF -DDEVLOG=ON
-- [cable ] Cable 0.2.14 initialized
-- [cable ] Build type: Release
-- [hunter] Calculating Toolchain-SHA1
-- [hunter] Calculating Config-SHA1
-- [hunter] HUNTER_ROOT: /root/.hunter
-- [hunter] [ Hunter-ID: 4b894e1 | Toolchain-ID: 652973c | Config-ID: cb395ce ]
-- [hunter] BOOST_ROOT: /root/.hunter/_Base/4b894e1/652973c/cb395ce/Install (ver.: 1.66.0)
-- [hunter] BOOST_ROOT: …
```
> fixes cmake linker error due to missing boost::thread dependency

- libpoolprotocols/stratum/EthStratumClient.cpp
Right now after resize extra nonce to 16 bytes, the std::stoul will raise exception "stoul argument out of range".
Because if server send extra nonce to "abcabc", after run enonce.resize(16, '0');
enonce will be "abcabc0000000000" in hex, it already exceed the max value of uint32_t, need to use the 64 bit version std::stoull to convert hex string to uint54_t type.
C++ reference
https://en.cppreference.com/w/cpp/string/basic_string/stoul
> Fix process extra nonce out of range exception

- libpoolprotocols/PoolURI.cpp
I saw a small bug in the [issues](https://github.com/ethereum-mining/ethminer/issues/1906), here is a small fix for it 
#1906
> fix lexical cast exeption on parse pool port

- libpoolprotocols/stratum/EthStratumClient.cpp
ethminer ignored the initial extranonce value and this caused incorrect shares until first extranonce update from pool.
fixes issues #1916 #1866 #1858
> Parse Nicehash extranonce after connecting to stratum

- libethash-cl/CLMiner.cpp
- libethcore/Miner.h
Intel's GPUs have historically been low power devices unsuitable for cyptomining, but upcoming Xe products (Artic Sound, Ponte Vecchio) look very applicable. One could also torture-test a NUC, maybe; I won't judge.
See also: https://www.anandtech.com/show/15188/analyzing-intels-discrete-xe-hpc-graphics-disclosure-ponte-vecchio/
Sample run on a Skull Canyon NUC with an Iris Pro Graphics 580 iGPU and the latest [NEO compute runtime](https://github.com/intel/compute-runtime):
```
$ ethminer/ethminer -G -P stratum1+ssl://<address.worker>@us1.ethermine.org:5555
ethminer 0.19.0-alpha.0-9+commit.a1256213
Build: linux/release/gnu
i 12:58:54 ethminer Configured pool us1.ethermine.org:5555
i 12:58:54 ethminer Selected pool us1.ethermine.org:5555
i 12:58:55 ethminer Stratum mode : Eth-Proxy …
```
> Support Intel GPUs

- libpoolprotocols/stratum/EthStratumClient.cpp
This fixes a segfault that happens when the connection is nulled.  In this situation the time loop will fail when you access the connection.
> fix seg fault

- libethash-cl/CLMiner.cpp
- libethash-cuda/CUDAMiner.cpp
- Reverse order of light cache and DAG allocation. DAG allocated first.
- Attempt to allocate ~80MB light cache buffer on GPU. If not enough
memory then allocate it on host.
- DAG generation will be much slower but we regain a little more space
for the DAG, which must reside on GPU.
> Extend the life of 4GB cards

- ethminer/main.cpp
This fixes #1923 The error arose from using a C++11 str in place of a C string.
> Fix to DBusInt::send() error.

- libethash-cuda/ethash_cuda_miner_kernel.cu
- libethash-cuda/ethash_cuda_miner_kernel.h
cleanup `ethash_calculate_dag_item()` 
* use `hash128_t`, remove `hash200_t`
* remove needless `shuffle(node_index)` loop
> CUDA: cleanup ethash_calculate_dag_item()

- libethash-cl/kernels/cl/ethash.cl
* fixed `MIX` macro for `LEGACY` support.
* simplified (partial revert commit: https://github.com/zawawawa/GatelessGateSharp/commit/1fb6179ed0112ddf27f2db5061a2347c8da57bf5)
> fix MIX() macro

- libpoolprotocols/PoolManager.cpp
fix epoch zero bug. (activated by `-M 0` or `-Z 0` options)
https://github.com/ethereum-mining/ethminer/issues/2003#issuecomment-690655783
~~~
$ ethminer -U -M 0
**ethminer 0.19.0-3
Build: linux/release/gnu
i 21:23:40 ethminer Selected pool localhost:0
i 21:23:40 ethminer Established connection to localhost:0
i 21:23:40 ethminer Spinning up miners...
cu 21:23:40 cuda-0   Using Pci Id : 03:00.0 P106-100 (Compute 6.1) Memory : 5.85 GB
i 21:23:40 sim      Epoch : -1 Difficulty : 4.29 Gh
i 21:23:40 sim      Job: 2072b99c… block 0 localhost:0
SIGSEGV encountered ...
stack trace:
backtrace() returned 8 addresses
ethminer/ethminer() [0x423d69]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0) [0x7f5aaf3614b0]
ethminer/ethminer() [0x6fbd76]
ethminer/ethminer() [0x6fe774]
ethminer/ethminer() [0x4bbbab] …
> fix epoch zero bug

- CMakeLists.txt
- docs/BUILD.md
- libethash-cl/CMakeLists.txt
> ENH: config option to use system OpenCL (for ROCm users)

- libethash-cl/kernels/cl/ethash.cl
MESA define `cl_amd_media_ops` but no `amd_bitalign()` found.
* define `amd_bitalign()` for it.
* define/restore `OPENCL_PLATFORM_*` and check `PLATFORM`.
See also https://github.com/openwall/john/issues/3454#issuecomment-436899959
> define amd_bitalign() for MESA

- libapicore/ApiServer.cpp
- libethcore/Miner.h
This PR just adds a few cosmetic tweaks. It changes the API's HTTP site slightly so the reported solutions are now in 
"Axxx:Rxxx:Fxxx" format, and rounds the power reports per card to 2 decimal places. It also adds that same rounding to the CLI status report line.
I wanted the former to help me follow long-term overclock stability when I can't easily scroll through the CLI output and check which card caused a rejected / failed share. The latter is just to reduce screen clutter that happens sometimes with floating point imprecision (cards would report 72.99999999999 watts, for example).
> Add rejected & failed share counts to HTTP API, clean up power reports

- libethash-cuda/CMakeLists.txt
Ampere graphic cards require compute capability 8.0 and 8.6.
Without this, trying to run this on my RTX 3090 fails.
Closes #2059, closes #2058
Should also close #2062 and close #2055 but I don't have an A100 to confirm unfortunately.
Thanks to @gorghino in his comment here: https://github.com/ethereum-mining/ethminer/issues/2059#issuecomment-711432189 Let me know if you want me add you as a [co-author on the commit](https://docs.github.com/en/free-pro-team@latest/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors)
See https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/ for the list of gencodes and archs.
> Support Ampere graphic cards using Cuda 11.0/11.1

- libethash-cl/kernels/cl/ethash.cl
~~this is a quick hack~~
use shared `__local` memory to speed up `GenerateDAG()`
~~It seems not optimized and efficient but~~ about twice faster than before.
> openCL: reduce GenerateDAG() time using shared __local memory

- CMakeLists.txt
- docs/BUILD.md
- libpoolprotocols/CMakeLists.txt
- scripts/install_cmake.sh
Adapte the Hunter to fix the obsolete links for hunter jobs (from ruslo to cpp-pm v0.23.300)
Update the BUILD.md to add the recommended g++ and cmake version 3.21.5
I am open for any task or edit,
Please let me know your feedback.
> Fixing the current Hunter issue to be make it can build again
